APPLICATION_NAME: zj2-lite-test
MYSQL_HOST: 127.0.0.1
MYSQL_PORT: 3308
MYSQL_DB_NAME: z2_db
MYSQL_USERNAME: root
MYSQL_PASSWORD: 123456
DB_POOL_SIZE: 300
REDIS_HOST: 127.0.0.1
REDIS_POST: 6379
REDIS_DATABASE: 0
REDIS_PASSWORD:
REDIS_POOL_SIZE: 100
ZJ2_DOC_ENABLE: true
ZJ2_DOC_TITLE: 'ZJ2是的'
ZJ2_CRYPT_SECRET:
ZJ2_WEB_INDEX:
ZJ2_WEB_CORS_ALLOWED_ORIGINS: '*'
ZJ2_WEB_CORS_ALLOWED_HEADERS: '*'
ZJ2_WEB_CORS_ALLOWED_METHODS: '*'
ZJ2_WEB_CORS_MAX_AGE: 1800
ZJ2_LOG_LEVEL: INFO
ZJ2_LOG_PATH: /logs